### ISSUE TITLE
Can not initialize version 2.*

### ISSUE THREAD

**Issue by migmira** [Ikos9/canvas-free-drawing#4]
The example code does not work, it throws the following error:

Uncaught TypeError: CanvasFreeDrawing is not a constructor

**Comment by Ikos9** [comment]
Are you installing it through npm/yarn or using the UMD file?

**Comment by Ikos9** [comment]
If you were also using the example file in the repo, just change the class init to `new CanvasFreeDrawing.default()`.

Hope this fix the problem, thank you for the bug report!
