### ISSUE TITLE
how can i fix  CanvasFreeDrawing is not a constructor

### ISSUE THREAD

**Issue by manoyna** [Ikos9/canvas-free-drawing#5]
hi  i run the example file and  have this error  CanvasFreeDrawing is not a constructor. how can i fix it thank you.

**Comment by Ikos9** [comment]
Ok, I've been able to reproduce it, I'm gonna fix it soon! In the meantime you can use the module version that is working fine.

**Comment by Ikos9** [comment]
I've found that you could make it work just changing the class init to `new CanvasFreeDrawing.default()`.

I'll update the example file to reflect the change, thank you for the bug report!
